version: '3'

services:
  postgresql:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=homestead
      - POSTGRES_DB=backend
    restart: always